### ISSUE TITLE
Error deploying or upgrading to v1.0.6

### ISSUE THREAD

**Issue by devans10** [purestorage/helm-charts#170]
Receiving the following error when I deploy or upgrade to v1.0.6 via Rancher. 

Wait helm template failed. 2020/02/11 12:28:55 warning: skipped value for arrays: Not a table. Error: parse error in "pure-csi/templates/node.yaml": template: pure-csi/templates/node.yaml:141: unexpected "=" in operand : exit status 1

**Comment by trevormeiss** [comment]
Hi Dave. Can you share your configuration for `defaultMountOpt` in `values.yaml`?
For example, here is the default value: https://github.com/purestorage/helm-charts/blob/d02823e03c2afac2b15c3aa81b09f237cb199e0a/pure-csi/values.yaml#L54-L55

**Comment by devans10** [comment]
I tried without specifying it, which should pick up the default and with specifying the value as below.

```
---
flasharray:
  sanType: FC
  defaultFSType: xfs
  defaultFSOpt: "-q"
  defaultMountOpt:
    - discard
  preemptAttachments: "true"
arrays:  
  FlashArrays:    
    - MgmtEndPoint: "xx.xx.xx.xx"      
      APIToken: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx"
```

**Comment by dsupure** [comment]
Hi Dave,
Does it work for the latter case you posted? Also, why do you have "`---`" ?  Do you append the value yaml to the other yaml file?

**Comment by devans10** [comment]
The "---" can be added or removed.  It doesn't affect the outcome.  What I posted works fine in version 1.0.5.  When I use the same in version 1.0.6, I receive the error.  I get the same with the below 

```
flasharray:
  sanType: FC
arrays:  
  FlashArrays:    
    - MgmtEndPoint: "xx.xx.xx.xx"      
      APIToken: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx"
```
