### ISSUE TITLE
Failed to initialize service object for metrics: replicasets.apps

### ISSUE THREAD

**Issue by yuha0** [purestorage/helm-charts#171]
With the `Role` defined in [install.sh](https://github.com/purestorage/helm-charts/blob/81a4f0e43206e2733c1e432f1089101a5c9d32ae/operator-csi-plugin/install.sh#L371), the operator logs the following error when starts:

```
{"level":"info","ts":1581545947.1596415,"logger":"cmd","msg":"failed to initialize service object for metrics: replicasets.apps \"pso-operator-697946fc65\" is forbidden: User \"system:serviceaccount:pure-yuhao:default\" cannot get resource \"replicasets\" in API group \"apps\" in the namespace \"pure-yuhao\"","Namespace":"pure-yuhao"}
```

I have to give it additional permission to `get` `replicasets`:

```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pso-operator
rules:
...
  - apiGroups:
    - apps
    resources:
    - deployments
    - daemonsets
    - statefulsets
    - replicasets <---------- added this
    verbs:
    - "*"
...
```
