### ISSUE TITLE
Clarify details in the docs for flashArrays

### ISSUE THREAD

**Issue by jayunit100** [purestorage/helm-charts#216]
@sdizer to add details ... 

```
flasharray:
  sanType: ISCSI
  defaultFSType: xfs
  defaultFSOpt: "-q"
  defaultMountOpt:
    - discard
  preemptAttachments: "true"
  iSCSILoginTimeout: 20
  iSCSIAllowedCIDR: ""

```

seems to be out of sync with the docs...
