### ISSUE TITLE
Support for Sharing a Volume Among Different Kubernetes Namespaces

### ISSUE THREAD

**Issue by zhaojunhua119** [purestorage/helm-charts#241]
## Requirement
We have a requirement to share a volume with different PODs in different Kubernetes namespaces.

## Problem
In Kubernetes, a volume can only be shared within one namespace by using PersistentVolumeClaim. It is not easy to share a purestorage volume among different namespaces.

## Workaround
Currently, we are using some workaround to share the same purestorage among different namespaces.  **Is there any problem with it?**

1.  Create a PersistentVolumeClaim in one namespace. Because we already have purestorage Storage Class being configured. a new PV and purestorage volume are provisioned.
2. run "kubectl get -o yaml <the_new_pv_name>" on the new PV
the output would look like this:
`````
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: pure/flex-norelabel
    fsType: nfs
    options:
      accessMode: exclusive
      backend: file
      labels: ""
      namespace: k8s
      volumeMode: ""
      volumeName: pvc-xxxx
  storageClassName: pure
`````
3. create a new PV in a different namespace with same flexVolume settings retrieved from the first PV.
because this new PV have the same flexVolume setting. It will actually use the same purestorage volume.
